export const WORD_LIST = [
  'ABHOR','ABIDE','ABODE','ABOUT','ABOVE','ABRUP','ABUSE','ABYSS','ACORN','ACRID',
  'ACTOR','ACUTE','ADAGE','ADMIT','ADOPT','ADORN','ADULT','ADEPT','AFTER','AGAIN',
  'AGENT','AGILE','AGLOW','AGONY','AGREE','AHEAD','AIDER','AISLE','ALARM','ALBUM',
  'ALERT','ALIGN','ALIKE','ALIVE','ALLOW','ALLOT','ALONE','ALONG','ALOFT','ALTER',
  'AMASS','AMAZE','AMEND','AMISS','AMPLE','AMPLY','AMUSE','ANGEL','ANGER','ANGLE',
  'ANGRY','ANGST','ANVIL','APART','APEXS','APING','APPLE','APPLY','ARBOR','ARENA',
  'ARGUE','ARISE','ARMOR','AROMA','ARROW','ASIDE','ASSET','ASHEN','ATLAS','ATTIC',
  'AUDIO','AUGUR','AURAS','AVAIL','AVOID','AWAKE','AWARD','AWARE','AXIOM','AZURE',
  'ADIEU','AURUM',

  'BADLY','BARGE','BASIC','BASIL','BASIS','BAYOU','BEACH','BEFIT','BEGAN','BEGIN',
  'BEGET','BEING','BELLY','BELOW','BENCH','BERTH','BINGE','BISON','BLACK','BLAME',
  'BLANK','BLEAK','BLIND','BLISS','BLOCK','BLOOD','BLUFF','BLUNT','BOARD','BOAST',
  'BOOST','BORNE','BOUND','BRAIN','BRACE','BRAND','BRAVE','BRAID','BREAD','BREAK',
  'BREED','BRIEF','BRING','BRISK','BROAD','BROKE','BROOM','BROWN','BUILD','BUDGE',
  'BULKY','BUNCH','BURST','BUYER',

  'CABIN','CABLE','CADET','CALIF','CAMEL','CANOE','CAPER','CARRY','CARVE','CATCH',
  'CAUSE','CEDAR','CHAIN','CHAIR','CHALK','CHART','CHASE','CHEAP','CHECK','CHEST',
  'CHIEF','CHILD','CHIME','CHINA','CHIRP','CHOOSE','CHUNK','CIDER','CIVIC','CIVIL',
  'CLAIM','CLASS','CLEAN','CLEAR','CLICK','CLIMB','CLONE','CLOCK','CLOSE','COACH',
  'COAST','COBRA','COMET','CONST','COULD','COUNT','COURT','COVER','CRAFT','CRANK',
  'CRASH','CRAZY','CREAM','CRIME','CRISP','CROSS','CROWD','CROWN','CUMIN','CURVE',
  'CYCLE',

  'DAILY','DANCE','DANDY','DATED','DEALT','DEATH','DEBUG','DEFER','DELAY','DEMON',
  'DENSE','DEPOT','DEPTH','DETER','DIRTY','DITCH','DIVED','DOING','DODGE','DOUBT',
  'DOZEN','DRAFT','DRAMA','DRAIN','DRAWN','DREAM','DRESS','DRILL','DRINK','DRIVE',
  'DROVE','DUSTY','DYING',

  'EAGER','EARLY','EARTH','ECLAT','EIGHT','ELATE','ELBOW','ELDER','ELITE','EMPTY',
  'EMBER','ENEMY','ENDOW','ENJOY','ENSUE','ENTER','ENTRY','EPOCH','EQUAL','ERODE',
  'ERROR','ESSAY','ETHER','ETHIC','EVENT','EVERY','EVADE','EXACT','EXALT','EXIST',
  'EXPEL','EXTOL','EXTRA',

  'FABLE','FACET','FAINT','FAITH','FALSE','FAULT','FETCH','FERAL','FEVER','FIBER',
  'FIELD','FIFTH','FIFTY','FIGHT','FINAL','FIRST','FIXED','FLASH','FLAIR','FLINT',
  'FLEET','FLOOR','FLUID','FLOUR','FLUSH','FOAMY','FOCUS','FORCE','FORGE','FORTH',
  'FORTY','FORUM','FOUND','FRAME','FRANK','FRAIL','FRAUD','FRESH','FRONT','FRUIT',
  'FULLY','FUNNY','FUGUE',

  'GAUZE','GENRE','GIANT','GIDDY','GIPSY','GIVEN','GLASS','GLEAN','GLINT','GLOBE',
  'GNOME','GOING','GRACE','GRADE','GRAFT','GRAND','GRANT','GRASP','GRASS','GREAT',
  'GREEN','GRIND','GROSS','GROUP','GROWN','GRUFF','GUARD','GUESS','GUEST','GUIDE',

  'HABIT','HAPPY','HARRY','HATCH','HAVOC','HEART','HEAVY','HEDGE','HENCE','HENRY',
  'HEFTY','HITCH','HOARD','HORSE','HOTEL','HOUSE','HOVER','HUMAN','HUSKY',

  'ICING','IDEAL','IMAGE','IMBUE','IMPEL','INDEX','INNER','INPUT','INERT','INFRA',
  'INLAY','IRATE','ISSUE','ISLET','IVORY','IDIOT',

  'JAPAN','JAUNT','JELLY','JIMMY','JOINT','JOKER','JONES','JUDGE','JUMBO',

  'KARMA','KNOWN','KNACK',

  'LABEL','LAPSE','LARGE','LASER','LATER','LATCH','LAUGH','LAYER','LEARN','LEASE',
  'LEAST','LEAVE','LEGAL','LEMUR','LEVEL','LEWIS','LIGHT','LIMIT','LINEN','LINKS',
  'LILAC','LIVES','LIVID','LOCAL','LOGIC','LOAMY','LOOSE','LOWER','LUCID','LUCKY',
  'LUMEN','LUNCH','LURID','LYING','LYMPH',

  'MAGIC','MAJOR','MAKER','MANGO','MANIA','MAPLE','MARCH','MARIA','MATCH','MAYBE',
  'MAYOR','MEANT','MEDIA','MELEE','MERCY','MERGE','MERIT','METAL','MIGHT','MINOR',
  'MINUS','MIRTH','MIXED','MODEL','MONEY','MONTH','MORAL','MOTOR','MOSSY','MOUNT',
  'MOUSE','MOUTH','MOVED','MOVIE','MURAL','MUSIC',

  'NACHO','NASAL','NEEDS','NEIGH','NEVER','NEWLY','NEXUS','NIGHT','NINJA','NOISE',
  'NOMAD','NORTH','NOTED','NOVEL','NURSE','NYLON',

  'OCCUR','OCEAN','ODDER','OFFER','OFTEN','OLIVE','OPINE','ORDER','ORBIT','ORGAN',
  'OTHER','OUGHT','OVERT',

  'PADDY','PAINT','PANEL','PAPER','PARCH','PARSE','PARTY','PEACE','PERKY','PESKY',
  'PETER','PETAL','PHASE','PHONE','PHOTO','PIECE','PIETY','PILOT','PITCH','PLACE',
  'PLAIN','PLANE','PLANT','PLATE','PLUCK','POINT','POISE','POUND','POWER','PRESS',
  'PRICE','PRIDE','PRIME','PRINT','PRIOR','PRIZE','PROOF','PROPS','PROUD','PROVE',
  'PSALM','PULSE','PUPIL',

  'QUAIL','QUARK','QUASH','QUEEN','QUERY','QUEUE','QUICK','QUIET','QUIRK','QUITE',

  'RADAR','RADIO','RAISE','RANGE','RAPID','RATIO','REACH','READY','REACT','REBUS',
  'RECAP','REFER','RELIC','REMIX','RENAL','RIGHT','RIGID','RHYME','RIVAL','RIVER',
  'ROBIN','ROGER','ROMAN','ROUGH','ROUND','ROUTE','ROYAL','RURAL','RUSTY',

  'SALTY','SCALE','SCALP','SCENE','SCOPE','SCORE','SENSE','SERUM','SERVE','SEVEN',
  'SEVER','SHADE','SHALL','SHAPE','SHARD','SHARE','SHARP','SHEET','SHELF','SHELL',
  'SHIFT','SHINE','SHIRT','SHOCK','SHOOT','SHORT','SHOWN','SIGHT','SILKY','SINCE',
  'SIREN','SIXTH','SIXTY','SIZED','SKILL','SLEEP','SLIDE','SLOPE','SMALL','SMART',
  'SMEAR','SMILE','SMIRK','SMITH','SMOKE','SNARE','SNEAK','SOLAR','SOLID','SOLVE',
  'SONIC','SORRY','SOUND','SOUTH','SPACE','SPARE','SPEAK','SPEED','SPEND','SPENT',
  'SPELT','SPIKE','SPLIT','SPOKE','SPORT','SQUAD','STAFF','STAGE','STAKE','STACK',
  'STAND','START','STATE','STEAM','STEEL','STICK','STILL','STOCK','STONE','STOOD',
  'STORE','STORM','STORY','STRIP','STUCK','STUDY','STUFF','STYLE','SUGAR','SUITE',
  'SUPER','SWEET','SWEEP','SWIRL',

  'TABLE','TAKEN','TAPER','TASTE','TAXES','TEACH','TEPID','TERRY','TEXAS','THANK',
  'THEFT','THEIR','THEME','THERE','THESE','THICK','THING','THINK','THIRD','THORN',
  'THOSE','THREE','THREW','THROW','TIDAL','TIGHT','TIMES','TITLE','TODAY','TOKEN',
  'TOPIC','TONIC','TOTAL','TOUCH','TOUGH','TORSO','TOWER','TOXIC','TRACK','TRADE',
  'TRAIN','TREAT','TREND','TRIAL','TRIED','TRIES','TRUCK','TRULY','TRUST','TRUTH',
  'TULIP','TWEAK','TWICE','TYPES',

  'ULCER','ULTRA','UMBRA','UNDER','UNDUE','UNION','UNITY','UNLIT','UNSET','UNTIL',
  'UPPER','UPSET','URBAN','USAGE','USUAL','USURP',

  'VALID','VALUE','VAPOR','VENOM','VIDEO','VIGOR','VINYL','VIRUS','VISIT','VITAL',
  'VOCAL','VOICE',

  'WAFER','WALTZ','WASTE','WATCH','WATER','WEARY','WHEEL','WHERE','WHICH','WHILE',
  'WHISK','WHITE','WHOLE','WHOSE','WIDEN','WISPY','WOKEN','WOMAN','WOMEN','WORLD',
  'WORRY','WORSE','WORST','WORTH','WOULD','WOUND','WRITE','WRONG','WROTE',

  'YACHT','YIELD','YEARN','YOUNG','YOUTH',

  'ZESTY'
];
